import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  fold: [
    {
      kind: 'choice',
      prompt: 'The player across declared riichi. You are in tenpai on a closed wait, for 1300: push or fold?',
      position: {
        hands: ['345m678p234s66p57s'],
        discards: [undefined, undefined, '9m1z'],
        riichi: [2],
        dealer: 3,
        turn: 1,
      },
      options: ['Push', 'Fold'],
      answer: 1,
      claim: { tenpai: true, goodWait: false, minRon: 1300 },
      why: 'Tenpai, but cheap and on a bad wait: two of three say fold.',
    },
    {
      kind: 'choice',
      prompt: 'The player across declared riichi. You are in tenpai on an edge wait, for 1000: push or fold?',
      position: {
        hands: ['234m567p44s12s'],
        melds: [[['pon', '666z']]],
        discards: [undefined, undefined, '9m1z'],
        riichi: [2],
        dealer: 3,
        turn: 1,
      },
      options: ['Fold', 'Push'],
      answer: 0,
      claim: { tenpai: true, goodWait: false, minRon: 1000 },
      why: 'Cheap, and an edge wait is a bad one: fold.',
    },
    {
      kind: 'choice',
      prompt:
        'The player across declared riichi. You are in tenpai for 1300, with one winning tile left: push or fold?',
      position: {
        hands: ['234m567m345p678s2s'],
        discards: [undefined, '2s', '9m1z', '2s'],
        riichi: [2],
        dealer: 3,
        turn: 1,
      },
      options: ['Push', 'Fold'],
      answer: 1,
      claim: { tenpai: true, goodWait: false, liveWaits: 1, minRon: 1300 },
      show: { ponds: [1, 3] },
      why: 'Tenpai, but cheap, and a wait with one tile left is as bad as it gets: fold.',
    },
  ],
  push: [
    {
      kind: 'choice',
      prompt: 'The player across declared riichi. You are in tenpai on a two-sided wait, for 2000: push or fold?',
      position: {
        hands: ['234m567m45p678s22s'],
        discards: [undefined, undefined, '9m1z'],
        riichi: [2],
        dealer: 3,
        turn: 1,
      },
      options: ['Push', 'Fold'],
      answer: 0,
      claim: { tenpai: true, goodWait: true, minRon: 2000 },
      why: 'Cheap, but in tenpai with a good wait: two of three say push.',
    },
    {
      kind: 'choice',
      prompt: 'The player across declared riichi. You are in tenpai on a closed wait, for 8000: push or fold?',
      position: {
        hands: ['234m234p234s88p46s'],
        discards: [undefined, undefined, '9m1z'],
        riichi: [2],
        dealer: 3,
        turn: 1,
        dora: '7p',
      },
      options: ['Fold', 'Push'],
      answer: 1,
      claim: { tenpai: true, goodWait: false, minRon: 8000 },
      why: 'A bad wait, but in tenpai for a mangan: two of three say push.',
    },
    {
      kind: 'choice',
      prompt:
        'The player across declared riichi. You are one tile from tenpai, with a closed and an edge shape: push or fold?',
      position: {
        hands: ['234m678p55s13p89s1z'],
        discards: [undefined, undefined, '9m2z'],
        riichi: [2],
        dealer: 3,
        turn: 1,
      },
      options: ['Push', 'Fold'],
      answer: 1,
      claim: { tenpai: false, shanten: 1, liveWaits: 8 },
      why: 'One tile away, push only with a big hand and two-sided shapes: both of these shapes are bad.',
    },
  ],
  ladder: [
    {
      kind: 'discard',
      prompt: 'The player across declared riichi. Nothing in your hand is genbutsu: discard the safest tile.',
      position: {
        hands: ['123m678p789s1p5p1z3z'],
        discards: [undefined, undefined, '4p2z'],
        riichi: [2],
        dealer: 3,
        turn: 0,
        draws: '8p',
      },
      goal: { safest: 2 },
      show: { ponds: [2] },
      why: '{1p} is suji of their {4p}, and a terminal: only a pair-based wait can still hit it.',
    },
    {
      kind: 'discard',
      prompt: 'The player across declared riichi. Nothing in your hand is genbutsu: discard the safest tile.',
      position: {
        hands: ['234m456p13m8s56p2z3z'],
        discards: [undefined, '77s', '1z9m', '77s'],
        riichi: [2],
        dealer: 3,
        turn: 0,
        draws: '6m',
      },
      goal: { safest: 2 },
      show: { ponds: [1, 2, 3] },
      why: 'All four {7s} are visible, so no two-sided wait can hit {8s}: it is no-chance.',
    },
    {
      kind: 'discard',
      prompt: 'The player across declared riichi. Nothing in your hand is genbutsu: discard the safest tile.',
      position: {
        hands: ['345m678s99m45s8p11z'],
        discards: [undefined, undefined, '2z5p9s'],
        riichi: [2],
        dealer: 3,
        turn: 0,
        draws: '3p',
      },
      goal: { safest: 2 },
      show: { ponds: [2] },
      why: '{8p} is suji of their {5p}; nothing higher on the ladder is in your hand.',
    },
  ],
  nothing: [
    {
      kind: 'choice',
      prompt: 'You are folding, and nothing in your hand is genbutsu or suji. Which is usually safer?',
      options: ['A {9s} nobody has discarded', 'A {5s} nobody has discarded'],
      answer: 0,
      why: 'A {5s} fits more waits than a {9s}: two-sided waits from both sides, and closed waits too.',
    },
    {
      kind: 'choice',
      prompt: 'You are folding with no safe tiles, and the dora is {5p}. Which is usually safer?',
      options: ['A {6p} nobody has discarded', 'A {6s} nobody has discarded'],
      answer: 1,
      why: 'Players keep the dora, so its neighbours win more often, and every win with it costs more.',
    },
    {
      kind: 'choice',
      prompt: 'You are folding with no safe tiles, holding {88s} and a single {8p}. Which do you throw first?',
      options: ['{8p}', '{8s}'],
      answer: 1,
      why: 'If the first {8s} passes, the second is genbutsu next turn.',
    },
  ],
};
