import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  closed: [
    {
      kind: 'fu',
      expect: 40,
      prompt: 'You are in riichi and win by ron on {2p}. Build the fu.',
      position: {
        hands: ['999p123m456s77m13p'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '2p',
        discard: true,
      },
      why: 'A closed wait and a concealed terminal triplet make this a 40 fu hand.',
    },
    {
      kind: 'fu',
      expect: 50,
      prompt: 'You win by ron on {4p}. Build the fu.',
      position: {
        hands: ['111s777z456m23p88m'],
        dealer: 3,
        turn: 2,
        draws: '4p',
        discard: true,
      },
      why: 'Two concealed triplets of terminals and honors add 8 each: 20 + 10 + 16 = 46, rounded up to 50.',
    },
    {
      kind: 'fu',
      expect: 40,
      prompt: 'You are in riichi and win by ron on {3s}. Build the fu.',
      position: {
        hands: ['345m678p234p12s55z'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '3s',
        discard: true,
      },
      why: 'A pair of white dragons and an edge wait add 2 each: 20 + 10 + 2 + 2 = 34, rounded up to 40.',
    },
  ],
  open: [
    {
      kind: 'fu',
      expect: 30,
      prompt: 'You called pon on white dragons and win by ron on {9s}. Build the fu.',
      position: {
        hands: ['234m678p11s99s'],
        melds: [[['pon', '555z']]],
        dealer: 3,
        turn: 1,
        draws: '9s',
        discard: true,
      },
      why: 'A triplet completed by ron counts as open.',
    },
    {
      kind: 'fu',
      expect: 40,
      prompt: 'You called pon on green dragons and win by ron on {6p}. Build the fu.',
      position: {
        hands: ['111s456m78p22p'],
        melds: [[['pon', '666z']]],
        dealer: 3,
        turn: 1,
        draws: '6p',
        discard: true,
      },
      why: 'No +10 for the open ron, but the {1s} triplet was in your hand: 20 + 4 + 8 = 32, rounded up to 40.',
    },
    {
      kind: 'fu',
      expect: 30,
      prompt: 'You called chii and win by ron on {8s}. Build the fu.',
      position: {
        hands: ['567p345s44p88s'],
        melds: [[['chii', '234m']]],
        dealer: 3,
        turn: 2,
        draws: '8s',
        discard: true,
      },
      why: 'The {8s} triplet was completed by ron, so it counts as an open simple: 20 + 2 = 22, rounded up to 30.',
    },
  ],
  tsumo: [
    {
      kind: 'fu',
      expect: 30,
      prompt: 'You draw {4s} and win. Build the fu.',
      position: {
        hands: ['111m456p789s55m23s'],
        dealer: 3,
        turn: 0,
        draws: '4s',
      },
      why: 'The triplet rules out pinfu, so the self-draw fu counts: 20 + 2 + 8 = 30.',
    },
    {
      kind: 'fu',
      expect: 30,
      prompt: 'You draw {2m} and win. Build the fu.',
      position: {
        hands: ['222p456m789s55s13m'],
        dealer: 3,
        turn: 0,
        draws: '2m',
      },
      why: 'The closed wait rules out pinfu, so the self-draw fu counts: 20 + 2 + 4 + 2 = 28, rounded up to 30.',
    },
    {
      kind: 'fu',
      expect: 40,
      prompt: 'You draw {9s} and win. Build the fu.',
      position: {
        hands: ['111m345p678s99s77p'],
        dealer: 3,
        turn: 0,
        draws: '9s',
      },
      why: 'You drew the {9s} yourself, so both terminal triplets are closed: 20 + 2 + 8 + 8 = 38, rounded up to 40.',
    },
  ],
  pinfu: [
    {
      kind: 'choice',
      prompt: 'How many fu is pinfu won by self-draw?',
      options: ['20', '22', '30'],
      answer: 0,
      why: 'Pinfu tsumo is fixed at 20 fu: the self-draw fu is not added.',
    },
    {
      kind: 'choice',
      prompt: 'How many fu is pinfu won by ron?',
      options: ['20', '30', '40'],
      answer: 1,
      why: '20 + 10 for the closed ron, and nothing else.',
    },
    {
      kind: 'choice',
      prompt: 'How many fu does the self-draw add to pinfu?',
      options: ['2', '10', 'None'],
      answer: 2,
      why: 'Pinfu by self-draw stays at 20 fu.',
    },
  ],
  pairs: [
    {
      kind: 'choice',
      prompt: 'How many fu is seven pairs?',
      options: ['20', '25', '30'],
      answer: 1,
      why: 'Seven pairs is always 25 fu, never rounded.',
    },
    {
      kind: 'choice',
      prompt: 'Seven pairs with a pair of dragons: how many fu?',
      options: ['25', '27', '30'],
      answer: 0,
      why: 'Seven pairs is fixed at 25 fu: nothing is added for the pairs.',
    },
    {
      kind: 'choice',
      prompt: 'A non-dealer wins by ron with seven pairs alone, 2 han. How many points?',
      options: ['1300', '1600', '2000'],
      answer: 1,
      why: '2 han at 25 fu, not rounded up to 30: 1600.',
    },
  ],
  estimate: [
    {
      kind: 'score',
      expect: '1 han 40 fu',
      prompt: 'A closed hand with all simples wins by ron on a closed wait. What is it worth?',
      position: { hands: ['234p567p456s88m46m'], dealer: 3, turn: 2, draws: '5m', discard: true },
      ask: 'han-fu',
      why: 'Closed, not pinfu, won by ron: about 40. Exactly: 20 + 10 for the closed ron + 2 for the wait, rounded up.',
    },
    {
      kind: 'score',
      expect: '1 han 30 fu',
      prompt: 'An open hand with all simples wins by ron. What is it worth?',
      position: {
        hands: ['567s345m66p78m'],
        melds: [[['chii', '234p']]],
        dealer: 3,
        turn: 2,
        draws: '6m',
        discard: true,
      },
      ask: 'han-fu',
      why: 'An open hand: about 30. Exactly: 20 with nothing to add, and an open hand is never below 30.',
    },
    {
      kind: 'score',
      expect: '2 han 50 fu',
      prompt: 'You are in riichi and win by ron with triplets of {9m} and red dragons in your hand. What is it worth?',
      position: {
        hands: ['999m777z345p56s22p'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      ask: 'han-fu',
      why: 'Count this one exactly: 20 + 10 for the closed ron + 8 for each closed triplet = 46, rounded up to 50.',
    },
  ],
};
