import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  safe: [
    {
      kind: 'discard',
      prompt: 'The player across declared riichi, then the player on your left discarded {7s}. Discard a completely safe tile.',
      position: {
        hands: ['23m456p789s55m3z7s1p'],
        discards: [undefined, undefined, '9m4p6s2z1z8m', '5z7s'],
        riichi: [2],
        passed: '7s',
        dealer: 3,
        turn: 0,
        draws: '8p',
      },
      goal: { safest: 2 },
      show: { ponds: [2, 3] },
      why: '{4p} is in their river, and they let {7s} pass after declaring: they can ron neither.',
    },
    {
      kind: 'discard',
      prompt: 'The player across declared riichi. Discard a completely safe tile.',
      position: {
        hands: ['13m234s678m4p7p99p5z'],
        discards: [undefined, undefined, '9s2z7p1z'],
        riichi: [2],
        dealer: 3,
        turn: 0,
        draws: '8s',
      },
      goal: { safest: 2 },
      show: { ponds: [2] },
      why: '{7p} is in their river: furiten keeps them from winning on it.',
    },
    {
      kind: 'discard',
      prompt: 'The player across declared riichi, and a turn later the player on your right discarded {8p}. Discard a completely safe tile.',
      position: {
        hands: ['56789m345s77s1p8p2z'],
        discards: [undefined, '3z8p', '1z5m9p6s'],
        riichi: [2],
        passed: '8p',
        dealer: 3,
        turn: 0,
        draws: '4p',
      },
      goal: { safest: 2 },
      show: { ponds: [1, 2] },
      why: '{5m} is in their river, and they let {8p} pass after declaring: both are genbutsu.',
    },
  ],
  suji: [
    {
      kind: 'choice',
      prompt: 'A riichi player discarded {4p}. Which tile is suji, safe from a two-sided wait?',
      options: ['{1p}', '{2p}', '{3p}'],
      answer: 0,
      why: 'A two-sided wait on {1p} would also wait on {4p}, which would make them furiten.',
    },
    {
      kind: 'choice',
      prompt: 'A riichi player discarded {6s}. Which tile is suji, safe from a two-sided wait?',
      options: ['{5s}', '{9s}', '{7s}'],
      answer: 1,
      why: 'Only {78s} waits two-sided on {9s}, and it also waits on {6s}, which would make them furiten.',
    },
    {
      kind: 'choice',
      prompt: 'A riichi player discarded {2p} and {8p}. Which tile is suji, safe from a two-sided wait?',
      options: ['{4p}', '{6p}', '{5p}'],
      answer: 2,
      why: '{34p} would also wait on {2p}, and {67p} on {8p}: both sides of {5p} are covered.',
    },
  ],
  wall: [
    {
      kind: 'pick',
      prompt: 'All four {7m} are visible. Tap the tiles in your hand that no two-sided wait can use.',
      position: { hands: ['789m123p456p789s5s'], discards: [undefined, '77m', '7m'], dealer: 3, turn: 1 },
      goal: 'no-chance',
      show: { ponds: [1, 2] },
      why: 'Only {67m} or {78m} could wait two-sided on {8m} or {9m}, and both need a {7m}.',
    },
    {
      kind: 'pick',
      prompt: 'All four {3p} are visible. Tap the tiles in your hand that no two-sided wait can use.',
      position: { hands: ['1223p456s789m55m9s'], discards: [undefined, '33p', '3p'], dealer: 3, turn: 1 },
      goal: 'no-chance',
      show: { ponds: [1, 2] },
      why: 'Only {23p} or {34p} could wait two-sided on {1p} or {2p}, and both need a {3p}.',
    },
    {
      kind: 'pick',
      prompt: 'All four {4p} are visible. Tap the tiles in your hand that no two-sided wait can use.',
      position: { hands: ['12346p789s345m77z'], discards: [undefined, '4p', '44p'], dealer: 3, turn: 1 },
      goal: 'no-chance',
      show: { ponds: [1, 2] },
      why: 'A two-sided wait on {2p} needs {34p}, and one on {3p} needs {45p}: both need a {4p}.',
    },
  ],
};
