import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  tanpin: [
    {
      kind: 'yaku',
      expect: ['tanyao', 'pinfu'],
      prompt: 'You win by ron on {4s}. Tap every yaku this hand has.',
      position: {
        hands: ['234m456p678s55m23s'],
        dealer: 3,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      why: 'Only 2 to 8 makes all simples; four sequences, a plain pair and a two-sided wait make pinfu.',
    },
    {
      kind: 'yaku',
      expect: ['tanyao', 'pinfu'],
      prompt: 'You win by ron on {8p}. Tap every yaku this hand has.',
      position: {
        hands: ['345p567s678m22s67p'],
        dealer: 3,
        turn: 2,
        draws: '8p',
        discard: true,
      },
      why: 'Only 2 to 8 makes all simples; four sequences, a plain pair and a two-sided wait make pinfu.',
    },
    {
      kind: 'yaku',
      expect: ['pinfu'],
      prompt: 'You win by ron on {5p}. Tap every yaku this hand has.',
      position: {
        hands: ['123m456s789p66s34p'],
        dealer: 3,
        turn: 2,
        draws: '5p',
        discard: true,
      },
      why: 'Four sequences, a plain pair and a two-sided wait make pinfu; the 1 and 9 rule out all simples.',
    },
  ],
  haku: [
    {
      kind: 'yaku',
      expect: ['yakuhaiWhite', 'menzenTsumo'],
      prompt: 'You draw {9s} and win. Which yaku does the hand have?',
      position: {
        hands: ['555z123m456p78s99s'],
        dealer: 3,
        turn: 0,
        draws: '9s',
      },
      why: 'The white dragon triplet, and self-draw with a closed hand.',
    },
    {
      kind: 'yaku',
      expect: ['yakuhaiGreen'],
      prompt: 'You win by ron on {6m}. Which yaku does the hand have?',
      position: {
        hands: ['666z234p567s45m88p'],
        dealer: 3,
        turn: 2,
        draws: '6m',
        discard: true,
      },
      why: 'The green dragon triplet; a ron is not self-draw.',
    },
    {
      kind: 'yaku',
      expect: ['yakuhaiRed'],
      prompt: 'You called pon on red dragons, then draw {6s} and win. Which yaku does the hand have?',
      position: {
        hands: ['234m678p45s99s'],
        melds: [[['pon', '777z']]],
        dealer: 3,
        turn: 0,
        draws: '6s',
      },
      why: 'The red dragon triplet counts open; self-draw needs a closed hand.',
    },
  ],
  wind: [
    {
      kind: 'yaku',
      show: { seat: true, round: true },
      expect: ['seatWind'],
      prompt: 'You sit South in the East round and win by ron. Which yaku?',
      position: {
        hands: ['222z123m456p78s99s'],
        dealer: 3,
        turn: 2,
        draws: '6s',
        discard: true,
      },
      why: 'South is your seat wind, so the triplet is a value triplet.',
    },
    {
      kind: 'yaku',
      show: { seat: true, round: true },
      expect: ['roundWind'],
      prompt: 'You sit West in the East round and win by ron. Which yaku?',
      position: {
        hands: ['111z345m678p23s66s'],
        dealer: 2,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      why: 'East is the round wind, so the triplet is a value triplet.',
    },
    {
      kind: 'yaku',
      show: { seat: true, round: true },
      expect: ['seatWind', 'roundWind'],
      prompt: 'You are the East dealer in the East round and win by ron. Which yaku?',
      position: {
        hands: ['111z234s567p45m88m'],
        dealer: 0,
        turn: 2,
        draws: '3m',
        discard: true,
      },
      why: 'East is both your seat wind and the round wind: the triplet counts twice.',
    },
  ],
  kanchan: [
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'Closed hand, no riichi, and {4s} is discarded. Can you win?',
      position: {
        hands: ['123m456p789s55m35s'],
        dealer: 3,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      why: 'A closed wait breaks pinfu, and the terminals rule out all simples.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'Closed hand, no riichi, and {3p} is discarded. Can you win?',
      position: {
        hands: ['234m567s789s44p12p'],
        dealer: 3,
        turn: 2,
        draws: '3p',
        discard: true,
      },
      why: 'An edge wait breaks pinfu, and the terminals rule out all simples.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'Closed hand, no riichi, and {5p} is discarded. Can you win?',
      position: {
        hands: ['123m456p789s234s5p'],
        dealer: 3,
        turn: 1,
        draws: '5p',
        discard: true,
      },
      why: 'A single wait on the pair breaks pinfu, and the terminals rule out all simples.',
    },
  ],
  opentan: [
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You called chii on {234m}, and {4s} is discarded. Can you win?',
      position: {
        hands: ['456p678s55m23s'],
        melds: [[['chii', '234m']]],
        dealer: 3,
        turn: 1,
        draws: '4s',
        discard: true,
      },
      why: 'All simples counts with an open hand on Riichi Arena.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You called pon on {666p}, and {7m} is discarded. Can you win?',
      position: {
        hands: ['234s567m33p56m'],
        melds: [[['pon', '666p']]],
        dealer: 3,
        turn: 1,
        draws: '7m',
        discard: true,
      },
      why: 'Every tile is 2 to 8: all simples, open or closed.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'You called chii on {567s}, and {6p} is discarded. Can you win?',
      position: {
        hands: ['234m345p78p99m'],
        melds: [[['chii', '567s']]],
        dealer: 3,
        turn: 1,
        draws: '6p',
        discard: true,
      },
      why: 'The {99m} pair rules out all simples, and pinfu needs a closed hand.',
    },
  ],
};
