import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  reasons: [
    {
      kind: 'choice',
      prompt: 'You are in tenpai, and not the dealer. Riichi or dama?',
      position: { hands: ['123m456p789s67s99m'], dealer: 3, turn: 1 },
      options: ['Riichi', 'Dama'],
      answer: 0,
      claim: { tenpai: true, goodWait: true, minRon: 1000 },
      why: 'A two-sided wait and pinfu: two reasons. Riichi turns 1000 into 2000 or more.',
    },
    {
      kind: 'choice',
      prompt: 'You are the dealer, in tenpai on a closed wait. Riichi or dama?',
      position: { hands: ['345m666p789p22z79s'], dealer: 0, turn: 1 },
      options: ['Dama', 'Riichi'],
      answer: 1,
      claim: { tenpai: true, goodWait: false, minRon: 0 },
      why: 'Being the dealer is reason enough, and without riichi this hand has no yaku for a ron.',
    },
    {
      kind: 'choice',
      prompt: 'You are not the dealer, in tenpai on a closed wait. Riichi or dama?',
      position: { hands: ['555z234m678p22s46s'], dealer: 3, turn: 1 },
      options: ['Riichi', 'Dama'],
      answer: 0,
      claim: { tenpai: true, goodWait: false, minRon: 1300 },
      why: 'The {555z} is a han already: riichi turns 1300 into 2600 or more.',
    },
  ],
  now: [
    {
      kind: 'choice',
      prompt: 'You just reached tenpai on a closed wait. Riichi now, or wait for a better shape?',
      position: { hands: ['234p567p456s88m46m'], dealer: 3, turn: 1 },
      options: ['Riichi now', 'Wait for a better shape'],
      answer: 0,
      claim: { tenpai: true, goodWait: false, minRon: 1300 },
      why: 'All simples is a han besides riichi, and the tiles that would improve the wait are few.',
    },
    {
      kind: 'choice',
      prompt: 'You just reached tenpai on an edge wait. Riichi now, or wait for a better shape?',
      position: { hands: ['345s567m222p99m89p'], dealer: 3, turn: 1 },
      options: ['Wait for a better shape', 'Riichi now'],
      answer: 1,
      claim: { tenpai: true, goodWait: false, minRon: 0 },
      why: 'Riichi is the only yaku this hand can get, and an edge wait has few ways to improve.',
    },
    {
      kind: 'choice',
      prompt: 'You just reached tenpai on a closed wait, with two dora. Riichi now, or wait for a better shape?',
      position: { hands: ['234m567m999p77s13p'], dealer: 3, turn: 1, dora: '6s' },
      options: ['Riichi now', 'Wait for a better shape'],
      answer: 0,
      claim: { tenpai: true, goodWait: false, minRon: 0 },
      show: { dora: true },
      why: 'Dora are not a yaku: without riichi this hand cannot win by ron.',
    },
  ],
  value: [
    {
      kind: 'discard',
      prompt: 'You drew {6s}, and the dora is {3s}. Which discard for riichi?',
      position: { hands: ['111m456p789p99m35s'], dealer: 3, turn: 0, draws: '6s', dora: '2s' },
      goal: 'judgment',
      only: '6s',
      show: { dora: true },
      why: 'Dropping the dora waits two-sided for 1300; keeping it waits on {4s} for 2600.',
    },
    {
      kind: 'discard',
      prompt: 'You drew the dora, {9m}. Which discard for riichi?',
      position: { hands: ['999p234m456s22s67m'], dealer: 3, turn: 0, draws: '9m', dora: '8m' },
      goal: 'judgment',
      only: '6m',
      show: { dora: true },
      why: 'Keeping {67m} waits two-sided for 1300; keeping the dora waits on {8m} for 2600.',
    },
    {
      kind: 'discard',
      prompt: 'You drew {6s} and hold two red fives; the dora is {3s}. Which discard for riichi?',
      position: { hands: ['340m406p678m88s35s'], dealer: 3, turn: 0, draws: '6s', dora: '2s' },
      goal: 'judgment',
      only: '3s',
      show: { dora: true },
      why: 'With two red fives the hand wins 8000 even without the {3s}: take the two-sided wait.',
    },
  ],
  dama: [
    {
      kind: 'choice',
      prompt: 'Late in the hand, this hand wins 8000 without riichi. Riichi or dama?',
      position: { hands: ['234m234p234s67s88p'], dealer: 3, turn: 1 },
      options: ['Riichi', 'Dama'],
      answer: 1,
      claim: { tenpai: true, minRon: 8000 },
      why: 'Riichi would add little to a mangan, but warns everyone and locks your hand.',
    },
    {
      kind: 'choice',
      prompt: 'You are in tenpai, but the hand has no yaku. Riichi or dama?',
      position: { hands: ['234m567p999s88m46s'], dealer: 3, turn: 1 },
      options: ['Riichi', 'Dama'],
      answer: 0,
      claim: { tenpai: true, minRon: 0 },
      why: 'Dama, it can only win by self-draw; riichi gives it a yaku for a ron.',
    },
    {
      kind: 'choice',
      prompt: 'Your closed wait has one tile left, and the hand has a yaku. Riichi or dama?',
      position: { hands: ['234m678m345p66s35s'], discards: [undefined, '4s9m', '44s'], dealer: 3, turn: 1 },
      options: ['Riichi', 'Dama'],
      answer: 1,
      claim: { tenpai: true, goodWait: false, liveWaits: 1, minRon: 1300 },
      show: { ponds: [1, 2] },
      why: 'Only one {4s} is left. Dama, you can still change the wait; riichi would lock you onto it.',
    },
  ],
};
