// Generated by scripts/calibrate.ts from 15000 bot-vs-bot games (seed "calibration").
// Skill 0.45 is pinned to 1500. Regenerate after changing the bots; do not edit by hand.
export const BOT_RATINGS: { skill: number; elo: number }[] = [
  { skill: 0, elo: 1283 },
  { skill: 0.15, elo: 1325 },
  { skill: 0.3, elo: 1413 },
  { skill: 0.45, elo: 1500 },
  { skill: 0.6, elo: 1558 },
  { skill: 0.75, elo: 1607 },
  { skill: 0.9, elo: 1630 },
  { skill: 1, elo: 1634 },
];
