// Generated by scripts/calibrate.ts from 15000 bot-vs-bot games (seed "calibration").
// Skill 0.15 is pinned to 1000. Regenerate after changing the bots; do not edit by hand.
export const BOT_RATINGS: { skill: number; elo: number }[] = [
  { skill: 0, elo: 958 },
  { skill: 0.15, elo: 1000 },
  { skill: 0.3, elo: 1088 },
  { skill: 0.45, elo: 1175 },
  { skill: 0.6, elo: 1233 },
  { skill: 0.75, elo: 1282 },
  { skill: 0.9, elo: 1305 },
  { skill: 1, elo: 1309 },
];
