import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  tsumo: [
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You drew {4s}. Can you win?',
      position: {
        hands: ['123m456p789s11z23s'],
        dealer: 3,
        turn: 0,
        draws: '4s',
      },
      why: 'Self-draw with a closed hand is a yaku by itself.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You drew {5p}. Can you win?',
      position: {
        hands: ['789m123s456s99m46p'],
        dealer: 3,
        turn: 0,
        draws: '5p',
      },
      why: 'Self-draw with a closed hand is a yaku by itself.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You drew {6s}. Can you win?',
      position: {
        hands: ['111p345m789s22z66s'],
        dealer: 3,
        turn: 0,
        draws: '6s',
      },
      why: '{666s} completes the hand, and self-draw with a closed hand is the yaku.',
    },
  ],
  ron: [
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'No riichi, and the player across discards {4s}. Can you win?',
      position: {
        hands: ['123m456p789s11z23s'],
        dealer: 3,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      why: 'By ron this closed hand has no yaku: no riichi, no simples-only, no value triplet.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'No riichi, and the player on your right discards {5p}. Can you win?',
      position: {
        hands: ['789m123s456s99m46p'],
        dealer: 3,
        turn: 1,
        draws: '5p',
        discard: true,
      },
      why: 'Self-draw would have been a yaku; by ron the hand has none.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'No riichi, but you hold a white dragon triplet, and the player across discards {2s}. Can you win?',
      position: {
        hands: ['555z234m678p99s34s'],
        dealer: 3,
        turn: 2,
        draws: '2s',
        discard: true,
      },
      why: 'The dragon triplet is a yaku in the hand, so ron is fine.',
    },
  ],
  riichi: [
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You declared riichi, and the player across discards {4s}. Can you win?',
      position: {
        hands: ['123m456p789s11z23s'],
        dealer: 3,
        riichi: [0],
        turn: 2,
        draws: '4s',
        discard: true,
      },
      why: 'Riichi is a yaku, so any closed tenpai hand with riichi can win.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You declared riichi, and the player on your right discards {5p}. Can you win?',
      position: {
        hands: ['789m123s456s99m46p'],
        dealer: 3,
        riichi: [0],
        turn: 1,
        draws: '5p',
        discard: true,
      },
      why: 'Riichi is a yaku, so any closed tenpai hand with riichi can win.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You declared riichi, and the player across discards {7m}. Can you win?',
      position: {
        hands: ['111p345s789s22z89m'],
        dealer: 3,
        riichi: [0],
        turn: 2,
        draws: '7m',
        discard: true,
      },
      why: 'Even on a one-tile edge wait, riichi is the yaku.',
    },
  ],
  simples: [
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'A closed hand of only tiles 2 to 8, no riichi, and the player across discards {3s}. Can you win?',
      position: {
        hands: ['234m456p678s55m33s'],
        dealer: 3,
        turn: 2,
        draws: '3s',
        discard: true,
      },
      why: 'All simples is the yaku: no riichi or self-draw needed.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'A closed hand of only tiles 2 to 8, no riichi, and the player on your right discards {5m}. Can you win?',
      position: {
        hands: ['345p567s678m22p46m'],
        dealer: 3,
        turn: 1,
        draws: '5m',
        discard: true,
      },
      why: 'All simples is the yaku: no riichi or self-draw needed.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'A closed hand, no riichi, and the player across discards {9s}. Can you win?',
      position: {
        hands: ['234m456p678s55m99s'],
        dealer: 3,
        turn: 2,
        draws: '9s',
        discard: true,
      },
      why: 'The {9s} is not a simple, so all simples is gone and nothing else is left.',
    },
  ],
  open: [
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You called pon on green dragons, and now {9s} is discarded. Can you win?',
      position: {
        hands: ['123m456p78s99s'],
        melds: [[['pon', '666z']]],
        dealer: 3,
        turn: 1,
        draws: '9s',
        discard: true,
      },
      why: 'The dragon triplet is the yaku.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You called chii on {678s}, and now {5m} is discarded. Can you win?',
      position: {
        hands: ['234m456p55s34m'],
        melds: [[['chii', '678s']]],
        dealer: 3,
        turn: 1,
        draws: '5m',
        discard: true,
      },
      why: 'Only tiles 2 to 8: all simples is the yaku, open or closed.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'You called pon on {999m}, and now {6p} is discarded. Can you win?',
      position: {
        hands: ['234s567p88m45p'],
        melds: [[['pon', '999m']]],
        dealer: 3,
        turn: 2,
        draws: '6p',
        discard: true,
      },
      why: 'No dragon or wind triplet, and {999m} rules out all simples: no yaku.',
    },
  ],
  dora: [
    {
      kind: 'choice',
      prompt: 'A complete hand has three dora and no yaku. Can it win?',
      options: ['Yes', 'No'],
      answer: 1,
      why: 'Dora only add value to a hand that already has a yaku.',
    },
    {
      kind: 'choice',
      prompt: 'A complete hand has riichi and two dora. Can it win?',
      options: ['Yes', 'No'],
      answer: 0,
      why: 'Riichi is the yaku; the dora add to its value.',
    },
    {
      kind: 'choice',
      prompt: 'Your winning hand holds a red five. What does it add?',
      options: ['A yaku', 'Value', 'Nothing'],
      answer: 1,
      why: 'A red five is a dora: it adds value, but it is never a yaku.',
    },
  ],
};
