import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  own: [
    {
      kind: 'can-win',
      expect: 'furiten',
      prompt:
        'You wait on {1s} or {4s} and discarded a {4s} earlier. The player on your right discards {4s}: can you win?',
      position: {
        hands: ['234m567p789s99s23s'],
        discards: ['4s'],
        dealer: 3,
        turn: 1,
        draws: '4s',
        discard: true,
      },
      show: { ponds: [0] },
      why: 'Your own {4s} is in your river.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You wait on {3p} or {6p}. The player across discards {6p}: can you win?',
      position: {
        hands: ['234m456s678p45p88s'],
        discards: ['1z9m2p'],
        dealer: 3,
        turn: 2,
        draws: '6p',
        discard: true,
      },
      show: { ponds: [0] },
      why: 'Neither {3p} nor {6p} is in your river.',
    },
    {
      kind: 'can-win',
      expect: 'furiten',
      prompt: 'You wait on {5m} or {8m}. The player on your right discards {8m}: can you win?',
      position: {
        hands: ['345p678s234s67m22p'],
        discards: ['9s1z8m'],
        dealer: 3,
        turn: 1,
        draws: '8m',
        discard: true,
      },
      show: { ponds: [0] },
      why: 'Your own {8m} is in your river.',
    },
  ],
  whole: [
    {
      kind: 'can-win',
      expect: 'furiten',
      prompt: 'You wait on {1s} or {4s} and discarded a {4s} earlier. The player across discards {1s}: can you win?',
      position: {
        hands: ['234m567p789s99s23s'],
        discards: ['4s'],
        dealer: 3,
        turn: 2,
        draws: '1s',
        discard: true,
      },
      show: { ponds: [0] },
      why: 'Furiten covers every tile you wait on, not only the one you discarded.',
    },
    {
      kind: 'can-win',
      expect: 'furiten',
      prompt: 'You wait on {3p} or {6p} and discarded a {3p} earlier. The player across discards {6p}: can you win?',
      position: {
        hands: ['234m456s678p45p88s'],
        discards: ['1z3p'],
        dealer: 3,
        turn: 2,
        draws: '6p',
        discard: true,
      },
      show: { ponds: [0] },
      why: 'The {3p} in your river makes the whole wait furiten, {6p} included.',
    },
    {
      kind: 'can-win',
      expect: 'furiten',
      prompt: 'You wait on {1s}, {4s} or {7s}. The player on your right discards {1s}: can you win?',
      position: {
        hands: ['123m567p23456s99s'],
        discards: ['9m7s'],
        dealer: 3,
        turn: 1,
        draws: '1s',
        discard: true,
      },
      show: { ponds: [0] },
      why: 'The {7s} in your river makes all three waits furiten.',
    },
  ],
  tsumo: [
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You wait on {1s} or {4s} and discarded a {4s} earlier. You draw {1s} yourself: can you win?',
      position: {
        hands: ['234m567p789s99s23s'],
        discards: ['4s'],
        dealer: 3,
        turn: 0,
        draws: '1s',
      },
      show: { ponds: [0] },
      why: 'Furiten only stops ron. Self-draw still wins.',
    },
    {
      kind: 'can-win',
      expect: 'furiten',
      prompt: 'You wait on {2p} or {5p} and discarded a {5p} earlier. The player across discards {2p}: can you win?',
      position: {
        hands: ['678m345s34p11s789p'],
        discards: ['5p'],
        dealer: 3,
        turn: 2,
        draws: '2p',
        discard: true,
      },
      show: { ponds: [0] },
      why: 'That is ron, and furiten stops it. Only a self-drawn {2p} or {5p} would win.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You wait on {2p} or {5p} and discarded a {5p} earlier. You draw {5p} yourself: can you win?',
      position: {
        hands: ['678m345s34p11s789p'],
        discards: ['5p'],
        dealer: 3,
        turn: 0,
        draws: '5p',
      },
      show: { ponds: [0] },
      why: 'Self-draw wins even on the tile in your river.',
    },
  ],
  avoid: [
    {
      kind: 'discard',
      prompt: 'You drew {5s}. Reach tenpai without being furiten.',
      position: {
        hands: ['234m567p789s99s23s'],
        discards: ['1s'],
        dealer: 3,
        turn: 0,
        draws: '5s',
      },
      goal: 'tenpai',
      only: '2s',
      show: { ponds: [0] },
      why: 'Keeping {35s} waits on {4s}, which is not in your river.',
    },
    {
      kind: 'discard',
      prompt: 'You drew {7p}. Reach tenpai without being furiten.',
      position: {
        hands: ['234s678m111z99m45p'],
        discards: ['3p'],
        dealer: 3,
        turn: 0,
        draws: '7p',
      },
      goal: 'tenpai',
      only: '4p',
      show: { ponds: [0] },
      why: 'Keeping {57p} waits on {6p}, which is not in your river.',
    },
    {
      kind: 'discard',
      prompt: 'You drew {1z}. Reach tenpai without being furiten.',
      position: {
        hands: ['123p678p789s4567m'],
        discards: ['9s7m'],
        dealer: 3,
        turn: 0,
        draws: '1z',
      },
      goal: 'tenpai',
      only: '4m7m',
      show: { ponds: [0] },
      why: 'A {1z} tanki is a smaller wait than {4567m}, but it is not furiten.',
    },
  ],
  temporary: [
    {
      kind: 'choice',
      prompt: 'You pass on a ron because the hand is cheap. When can you ron again?',
      options: ['Right away', 'After your next discard', 'Never this hand'],
      answer: 1,
      why: 'Passing makes you temporarily furiten until your own next discard.',
    },
    {
      kind: 'choice',
      prompt: 'You are in riichi and let a winning tile pass. When can you ron again?',
      options: ['Never this hand', 'After your next discard', 'Right away'],
      answer: 0,
      why: 'In riichi you can no longer change your hand, so the furiten lasts the whole hand.',
    },
    {
      kind: 'choice',
      prompt: 'You pass on a ron, and before your turn the next player discards another winning tile. Can you ron it?',
      options: ['Yes', 'Only if it is a different tile', 'No'],
      answer: 2,
      why: 'Temporary furiten lasts until your own next discard, whoever discards.',
    },
  ],
};
