import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  pon: [
    {
      kind: 'call',
      prompt: 'The player on your right discards {5z}, and you hold a pair of them. Call or pass?',
      position: {
        hands: ['55z123m456p78s99s1m'],
        dealer: 3,
        turn: 1,
        draws: '5z',
        discard: true,
      },
      goal: 'pon',
      show: { ponds: [1] },
      why: 'A dragon triplet is a yaku, so the hand can still win after calling.',
    },
    {
      kind: 'call',
      prompt: 'The player across discards {6z}, and you hold a pair of them. Call or pass?',
      position: {
        hands: ['66z234p567s45m88s1m'],
        dealer: 3,
        turn: 2,
        draws: '6z',
        discard: true,
      },
      goal: 'pon',
      show: { ponds: [2] },
      why: 'A dragon triplet is a yaku, so the hand can still win after calling.',
    },
    {
      kind: 'call',
      prompt: 'The player on your left discards {7z}, and you hold a pair of them. Call or pass?',
      position: {
        hands: ['77z345m678p23s99p7s'],
        dealer: 3,
        turn: 3,
        draws: '7z',
        discard: true,
      },
      goal: 'pon',
      show: { ponds: [3] },
      why: 'Pon takes a discard from any seat, and the red dragon triplet keeps a yaku.',
    },
  ],
  chii: [
    {
      kind: 'call',
      prompt: 'The player on your left discards {5m}. Complete {34m} with it.',
      position: {
        hands: ['34m678p12s555z99p7z'],
        dealer: 3,
        turn: 3,
        draws: '5m',
        discard: true,
      },
      goal: 'chii',
      show: { ponds: [3] },
      why: 'The hand already has a dragon triplet, so it keeps a yaku when open.',
    },
    {
      kind: 'call',
      prompt: 'The player on your left discards {7p}. Complete {68p} with it.',
      position: {
        hands: ['68p123s666z44m99s5m'],
        dealer: 3,
        turn: 3,
        draws: '7p',
        discard: true,
      },
      goal: 'chii',
      show: { ponds: [3] },
      why: 'The hand already has a dragon triplet, so it keeps a yaku when open.',
    },
    {
      kind: 'call',
      prompt: 'The player on your left discards {4s}. Complete {56s} with it.',
      position: {
        hands: ['56s234m678p55p378m'],
        dealer: 3,
        turn: 3,
        draws: '4s',
        discard: true,
      },
      goal: 'chii',
      show: { ponds: [3] },
      why: 'Every tile is 2 to 8, so all simples keeps a yaku when open.',
    },
  ],
  who: [
    {
      kind: 'choice',
      prompt: 'Who can you chii from?',
      options: ['Anyone', 'Only the player on your left', 'Only the player across'],
      answer: 1,
      why: 'Chii only takes the discard of the player just before you.',
    },
    {
      kind: 'choice',
      prompt: 'Who can you pon from?',
      options: ['Only the player on your left', 'Only the player on your right', 'Anyone'],
      answer: 2,
      why: "Pon takes any player's discard; play then continues from you.",
    },
    {
      kind: 'choice',
      prompt: 'The player across discards the tile your sequence needs. Can you chii it?',
      options: ['Yes', 'No'],
      answer: 1,
      why: 'Only the discard of the player on your left can complete a sequence.',
    },
  ],
  kan: [
    {
      kind: 'call',
      prompt: 'You hold three red dragons, and the player on your right discards the fourth. Make a quad.',
      position: {
        hands: ['777z123m456p67s99s'],
        dealer: 3,
        turn: 1,
        draws: '7z',
        discard: true,
      },
      goal: 'daiminkan',
      show: { ponds: [1] },
      why: 'A kan: you draw a replacement tile, and a new dora indicator is turned over. Open kans are best when, like here, you are in tenpai with a good wait.',
    },
    {
      kind: 'call',
      prompt: 'You hold three white dragons, and the player across discards the fourth. Make a quad.',
      position: {
        hands: ['555z234s678m34p11m'],
        dealer: 3,
        turn: 2,
        draws: '5z',
        discard: true,
      },
      goal: 'daiminkan',
      show: { ponds: [2] },
      why: 'You are in tenpai on {2p} or {5p}, a good wait: a kan adds a replacement draw and a dora indicator.',
    },
    {
      kind: 'call',
      prompt: 'You hold three green dragons, and the player on your left discards the fourth. Make a quad.',
      position: {
        hands: ['666z345p789m56s22p'],
        dealer: 3,
        turn: 3,
        draws: '6z',
        discard: true,
      },
      goal: 'daiminkan',
      show: { ponds: [3] },
      why: "Tenpai on {4s} or {7s}, a good wait, so the kan is worth it. Any seat's discard can make one.",
    },
  ],
  priority: [
    {
      kind: 'choice',
      prompt: 'One player calls pon and another calls chii on the same tile. Who gets it?',
      options: ['The pon', 'The chii', 'Whoever spoke first'],
      answer: 0,
      why: 'Ron beats pon and kan, and those beat chii.',
    },
    {
      kind: 'choice',
      prompt: 'One player calls pon and another calls ron on the same tile. Who gets it?',
      options: ['The pon', 'The ron', 'Whoever spoke first'],
      answer: 1,
      why: 'A win beats every call.',
    },
    {
      kind: 'choice',
      prompt: 'One player calls chii and another calls kan on the same tile. Who gets it?',
      options: ['Whoever spoke first', 'The chii', 'The kan'],
      answer: 2,
      why: 'Kan ranks with pon, and both beat chii.',
    },
  ],
  trap: [
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'You called chii on {123m}, and now {8s} is discarded. Can you win?',
      position: {
        hands: ['456p789s55m67s'],
        melds: [[['chii', '123m']]],
        dealer: 3,
        turn: 1,
        draws: '8s',
        discard: true,
      },
      why: 'Open, with terminals and no value tiles, nothing is left. Kept closed, this hand could have declared riichi.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'You called pon on {999p}, and now {6s} is discarded. Can you win?',
      position: {
        hands: ['234m567s22p45s'],
        melds: [[['pon', '999p']]],
        dealer: 3,
        turn: 2,
        draws: '6s',
        discard: true,
      },
      why: 'The {999p} rules out all simples, and there is no value triplet: no yaku. Closed, riichi would have made it winnable.',
    },
    {
      kind: 'can-win',
      expect: 'yes',
      prompt: 'You called chii on {234p}, and now {6s} is discarded. Can you win?',
      position: {
        hands: ['567m345s66p78s'],
        melds: [[['chii', '234p']]],
        dealer: 3,
        turn: 1,
        draws: '6s',
        discard: true,
      },
      why: 'Every tile is 2 to 8: all simples is a yaku the open hand keeps.',
    },
  ],
};
