import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  honitsu: [
    {
      kind: 'yaku',
      expect: ['yakuhaiWhite', 'honitsu'],
      prompt: 'You called pon on white dragons and win by ron on {6m}. Tap every yaku.',
      position: {
        hands: ['234567m99m78m'],
        melds: [[['pon', '555z']]],
        dealer: 3,
        turn: 1,
        draws: '6m',
        discard: true,
      },
      distractors: ['tanyao', 'chinitsu', 'ittsu', 'toitoi', 'chanta'],
      why: 'One suit plus honors is a half flush; the dragon triplet is a second yaku.',
    },
    {
      kind: 'yaku',
      expect: ['honitsu'],
      prompt: 'Closed hand, and you win by ron on {6p}. Tap every yaku.',
      position: {
        hands: ['234p678p999p33z45p'],
        dealer: 3,
        turn: 2,
        draws: '6p',
        discard: true,
      },
      distractors: ['tanyao', 'chinitsu', 'ittsu', 'pinfu', 'yakuhaiWhite'],
      why: 'Circles plus a pair of West is a half flush; the triplet rules out pinfu.',
    },
    {
      kind: 'yaku',
      expect: ['chinitsu', 'tanyao'],
      prompt: 'You called chii on {234s} and win by ron on {5s}. Tap every yaku.',
      position: {
        hands: ['567s888s22s34s'],
        melds: [[['chii', '234s']]],
        dealer: 3,
        turn: 1,
        draws: '5s',
        discard: true,
      },
      distractors: ['honitsu', 'ittsu', 'toitoi', 'pinfu'],
      why: 'Only bamboo is a full flush, and only 2 to 8 adds all simples.',
    },
  ],
  pairs: [
    {
      kind: 'yaku',
      expect: ['chiitoitsu', 'menzenTsumo'],
      prompt: 'You draw {7z} and win. Tap every yaku.',
      position: { hands: ['1133m5577p2266s7z'], dealer: 3, turn: 0, draws: '7z' },
      distractors: ['toitoi', 'iipeikou', 'honitsu', 'yakuhaiRed'],
      why: 'Seven pairs, and self-draw with a closed hand.',
    },
    {
      kind: 'yaku',
      expect: ['chiitoitsu', 'tanyao'],
      prompt: 'You win by ron on {7p}. Tap every yaku.',
      position: { hands: ['2244m6688p3355s7p'], dealer: 3, turn: 2, draws: '7p', discard: true },
      distractors: ['toitoi', 'iipeikou', 'pinfu', 'menzenTsumo'],
      why: 'Seven pairs, all of them 2 to 8: all simples too.',
    },
    {
      kind: 'yaku',
      expect: ['chiitoitsu', 'honitsu'],
      prompt: 'You win by ron on {6z}. Tap every yaku.',
      position: { hands: ['1133557799p22z6z'], dealer: 3, turn: 2, draws: '6z', discard: true },
      distractors: ['toitoi', 'chinitsu', 'yakuhaiGreen', 'menzenTsumo'],
      why: 'Seven pairs in circles plus honors: a half flush too. A pair of green dragons is not a triplet.',
    },
  ],
  straight: [
    {
      kind: 'yaku',
      expect: ['ittsu', 'pinfu'],
      prompt: 'You win by ron on {4s}. Tap every yaku.',
      position: {
        hands: ['123456789p23s55m'],
        dealer: 3,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      distractors: ['tanyao', 'sanshokuDoujun', 'chinitsu', 'iipeikou'],
      why: '1 to 9 in one suit is a pure straight; the rest of the hand also makes pinfu.',
    },
    {
      kind: 'yaku',
      expect: ['sanshokuDoujun', 'pinfu', 'tanyao'],
      prompt: 'You win by ron on {8m}. Tap every yaku.',
      position: {
        hands: ['345m345p345s67m22s'],
        dealer: 3,
        turn: 2,
        draws: '8m',
        discard: true,
      },
      distractors: ['ittsu', 'iipeikou', 'chinitsu', 'honitsu'],
      why: '{345m} {345p} {345s} is a mixed triple sequence; the hand is also pinfu and all simples.',
    },
    {
      kind: 'yaku',
      expect: ['ittsu'],
      prompt: 'You called chii on {123s} and win by ron on {8m}. Tap every yaku.',
      position: {
        hands: ['456s789s55p67m'],
        melds: [[['chii', '123s']]],
        dealer: 3,
        turn: 1,
        draws: '8m',
        discard: true,
      },
      distractors: ['tanyao', 'sanshokuDoujun', 'pinfu', 'honitsu'],
      why: 'The called {123s} still counts for the pure straight, now 1 han; pinfu needs a closed hand.',
    },
  ],
  triplets: [
    {
      kind: 'yaku',
      show: { seat: true, round: true },
      expect: ['toitoi', 'roundWind'],
      prompt: 'Two pons called, and you win by ron on {1z}. Tap every yaku.',
      position: {
        hands: ['777s99m11z'],
        melds: [
          [
            ['pon', '222m'],
            ['pon', '555p'],
          ],
        ],
        dealer: 3,
        turn: 1,
        draws: '1z',
        discard: true,
      },
      distractors: ['sanankou', 'honroutou', 'tanyao', 'seatWind'],
      why: 'Four triplets make all triplets; East is the round wind.',
    },
    {
      kind: 'yaku',
      expect: ['toitoi', 'tanyao'],
      prompt: 'Two pons called, and you win by ron on {2p}. Tap every yaku.',
      position: {
        hands: ['444p66s22p'],
        melds: [
          [
            ['pon', '333m'],
            ['pon', '888s'],
          ],
        ],
        dealer: 3,
        turn: 1,
        draws: '2p',
        discard: true,
      },
      distractors: ['sanankou', 'honroutou', 'pinfu', 'chinitsu'],
      why: 'Four triplets make all triplets, and every tile is 2 to 8.',
    },
    {
      kind: 'yaku',
      expect: ['toitoi', 'yakuhaiWhite', 'yakuhaiRed'],
      prompt: 'Two pons called, and you win by ron on {5z}. Tap every yaku.',
      position: {
        hands: ['111p44s55z'],
        melds: [
          [
            ['pon', '777z'],
            ['pon', '999m'],
          ],
        ],
        dealer: 3,
        turn: 1,
        draws: '5z',
        discard: true,
      },
      distractors: ['sanankou', 'honroutou', 'tanyao', 'chanta'],
      why: 'Four triplets make all triplets, and each dragon triplet is a value triplet.',
    },
  ],
  closedonly: [
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'You called chii on {123m} and hold another {123m}. Can you win on {9s}?',
      position: {
        hands: ['123m456p55s78s'],
        melds: [[['chii', '123m']]],
        dealer: 3,
        turn: 1,
        draws: '9s',
        discard: true,
      },
      why: 'Two identical sequences (iipeikou) only count in a closed hand.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'You called chii on {789p} and hold a two-sided wait. Can you win on {8s}?',
      position: {
        hands: ['123s456m22m67s'],
        melds: [[['chii', '789p']]],
        dealer: 3,
        turn: 2,
        draws: '8s',
        discard: true,
      },
      why: 'Pinfu only counts in a closed hand, and the terminals rule out all simples.',
    },
    {
      kind: 'can-win',
      expect: 'no-yaku',
      prompt: 'You called pon on {999m} and draw {4p}. Can you win?',
      position: {
        hands: ['123s678s55p23p'],
        melds: [[['pon', '999m']]],
        dealer: 3,
        turn: 0,
        draws: '4p',
      },
      why: 'Self-draw is only a yaku with a closed hand.',
    },
  ],
};
