import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  tsumo: [
    {
      kind: 'score',
      show: { seat: true },
      expect: '700 / 1300',
      prompt: 'You draw {4s} and win. What do the others pay?',
      position: {
        hands: ['234m456p678s55m23s'],
        dealer: 3,
        turn: 0,
        draws: '4s',
      },
      ask: 'points',
      why: 'Self-draw, all simples and pinfu: 3 han 20 fu. The dealer pays the larger share.',
    },
    {
      kind: 'score',
      show: { seat: true },
      expect: '300 / 500',
      prompt: 'You draw {2s} and win. What do the others pay?',
      position: {
        hands: ['234m567p345s99p13s'],
        dealer: 2,
        turn: 0,
        draws: '2s',
      },
      ask: 'points',
      why: 'Self-draw only: 1 han 30 fu. The dealer pays 500, the others 300 each.',
    },
    {
      kind: 'score',
      show: { seat: true },
      expect: '1300 / 2600',
      prompt: 'You are in riichi, draw {6m} and win. What do the others pay?',
      position: {
        hands: ['345p678s234s66p45m'],
        riichi: [0],
        dealer: 1,
        turn: 0,
        draws: '6m',
      },
      ask: 'points',
      why: 'Riichi, self-draw, all simples and pinfu: 4 han 20 fu. The dealer pays twice as much.',
    },
  ],
  gain: [
    {
      kind: 'score',
      show: { seat: true, counters: true },
      expect: '3600',
      prompt: 'Two counters and one riichi stick are on the table. You win by ron on {4s}: what do you collect?',
      position: {
        hands: ['234m456p678s55m23s'],
        dealer: 3,
        honba: 2,
        riichiSticks: 1,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      ask: 'gain',
      why: '2000 for the hand, 600 for the counters, 1000 for the stick.',
    },
    {
      kind: 'score',
      show: { seat: true, counters: true },
      expect: '4300',
      prompt: 'One counter and two riichi sticks are on the table. You win by ron on {6p}: what do you collect?',
      position: {
        hands: ['345s678m234p77s45p'],
        dealer: 3,
        honba: 1,
        riichiSticks: 2,
        turn: 2,
        draws: '6p',
        discard: true,
      },
      ask: 'gain',
      why: '2000 for the hand, 300 for the counter, 2000 for the sticks.',
    },
    {
      kind: 'score',
      show: { seat: true, counters: true },
      expect: '3000',
      prompt: 'Three counters and one riichi stick are on the table. You draw {2s} and win: what do you collect?',
      position: {
        hands: ['234m567p345s99p13s'],
        dealer: 2,
        honba: 3,
        riichiSticks: 1,
        turn: 0,
        draws: '2s',
      },
      ask: 'gain',
      why: '1100 for the hand, 900 for the counters (300 from each player), 1000 for the stick.',
    },
  ],
  alone: [
    {
      kind: 'choice',
      prompt: 'The wall runs out and only you are in tenpai. What do you receive?',
      options: ['1000', '1500', '3000'],
      answer: 2,
      why: 'The three noten players pay 1000 each.',
    },
    {
      kind: 'choice',
      prompt: 'The wall runs out and only one opponent is in tenpai. What do you pay?',
      options: ['1000', '1500', '3000'],
      answer: 0,
      why: 'The three noten players share the 3000: 1000 each.',
    },
    {
      kind: 'choice',
      prompt: 'The wall runs out and nobody is in tenpai. What do you pay?',
      options: ['1000', 'Nothing', '3000'],
      answer: 1,
      why: 'With nobody in tenpai there is nobody to pay.',
    },
  ],
  two: [
    {
      kind: 'choice',
      prompt: 'At the draw two players are in tenpai. What does each noten player pay?',
      options: ['1000', '1500', '3000'],
      answer: 1,
      why: '3000 moves in total: each noten player pays 1500, each tenpai player gets 1500.',
    },
    {
      kind: 'choice',
      prompt: 'At the draw three players are in tenpai. What does the noten player pay?',
      options: ['1000', '1500', '3000'],
      answer: 2,
      why: 'The one noten player pays the whole 3000, 1000 to each.',
    },
    {
      kind: 'choice',
      prompt: 'At the draw three players are in tenpai. What does each of them receive?',
      options: ['1000', '1500', '3000'],
      answer: 0,
      why: 'The 3000 from the noten player is split three ways.',
    },
  ],
  dealer: [
    {
      kind: 'choice',
      prompt: 'The dealer is in tenpai when the wall runs out. Who deals next?',
      options: ['The same dealer, with a counter added', 'The next player'],
      answer: 0,
      why: 'A tenpai dealer keeps the seat.',
    },
    {
      kind: 'choice',
      prompt: 'The dealer is noten when the wall runs out. Who deals next?',
      options: ['The same dealer, with a counter added', 'The next player'],
      answer: 1,
      why: 'A noten dealer loses the seat.',
    },
    {
      kind: 'choice',
      prompt: 'The dealer wins by ron. Who deals next?',
      options: ['The next player', 'The same dealer, with a counter added'],
      answer: 1,
      why: 'A winning dealer keeps the seat.',
    },
  ],
};
