import type { ExerciseSet } from '../../context';

export const exercises: Record<string, ExerciseSet> = {
  count: [
    {
      kind: 'score',
      expect: '3 han',
      prompt: 'You are in riichi and win by ron on {4s}. How many han is the hand worth?',
      position: {
        hands: ['234m456p678s55m23s'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      ask: 'han',
      why: 'With no dora, the han are just the yaku added up. Keep the 30 fu for the next step.',
    },
    {
      kind: 'score',
      expect: '2 han',
      prompt: 'You are in riichi and win by ron on {5m}. How many han is the hand worth?',
      position: {
        hands: ['777z234p567s34m99p'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '5m',
        discard: true,
      },
      ask: 'han',
      why: 'Riichi and the red dragon triplet: 1 han each.',
    },
    {
      kind: 'score',
      show: { dora: true },
      expect: '4 han',
      prompt: 'You are in riichi and win by ron on {9s}. How many han is the hand worth?',
      position: {
        hands: ['123p678s234m66p78s'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '9s',
        discard: true,
        dora: '5p',
      },
      ask: 'han',
      why: 'Riichi and pinfu are 2 han, and the pair of {6p} adds 2 dora.',
    },
  ],
  points: [
    {
      kind: 'score',
      show: { seat: true },
      expect: '3900',
      prompt: 'You win by ron with 3 han and 30 fu. How many points does the discarder pay?',
      position: {
        hands: ['234m456p678s55m23s'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '4s',
        discard: true,
      },
      ask: 'points',
      why: '3 han 30 fu for a non-dealer is 3900.',
    },
    {
      kind: 'score',
      show: { seat: true },
      expect: '2600',
      prompt: 'You win by ron with 2 han and 40 fu. How many points does the discarder pay?',
      position: {
        hands: ['777z234p567s34m99p'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '5m',
        discard: true,
      },
      ask: 'points',
      why: '2 han 40 fu for a non-dealer is 2600.',
    },
    {
      kind: 'score',
      show: { seat: true },
      expect: '2000',
      prompt: 'You win by ron with 2 han and 30 fu. How many points does the discarder pay?',
      position: {
        hands: ['123p678s234m88p78s'],
        riichi: [0],
        dealer: 3,
        turn: 2,
        draws: '9s',
        discard: true,
      },
      ask: 'points',
      why: '2 han 30 fu for a non-dealer is 2000.',
    },
  ],
  dealer: [
    {
      kind: 'score',
      show: { seat: true },
      expect: '1300 all',
      prompt: 'You are the dealer and win by self-draw with 2 han and 40 fu. What does each player pay?',
      position: {
        hands: ['555z123m456p78s99s'],
        dealer: 0,
        turn: 0,
        draws: '9s',
      },
      ask: 'points',
      why: 'Dealer self-draw, 2 han 40 fu: 1300 from each player.',
    },
    {
      kind: 'score',
      show: { seat: true },
      expect: '5800',
      prompt: 'You are the dealer and win by ron with 3 han and 30 fu. What does the discarder pay?',
      position: {
        hands: ['345m678p234s55p67m'],
        riichi: [0],
        dealer: 0,
        turn: 2,
        draws: '8m',
        discard: true,
      },
      ask: 'points',
      why: 'A non-dealer would get 3900; the dealer gets 1.5 times that, 5800.',
    },
    {
      kind: 'score',
      show: { seat: true },
      expect: '2000 all',
      prompt: 'You are the dealer and win by self-draw with 3 han and 30 fu. What does each player pay?',
      position: {
        hands: ['666z234p567s34m99p'],
        riichi: [0],
        dealer: 0,
        turn: 0,
        draws: '2m',
      },
      ask: 'points',
      why: 'Dealer self-draw, 3 han 30 fu: 2000 from each player.',
    },
  ],
  mangan: [
    {
      kind: 'choice',
      prompt: 'What is a non-dealer 4 han 40 fu hand worth?',
      options: ['5200', '7700', '8000 (mangan)'],
      answer: 2,
      why: 'Above 2000 base points the score is capped at a mangan.',
    },
    {
      kind: 'choice',
      prompt: 'What is a non-dealer 5 han 30 fu hand worth?',
      options: ['7700', '8000 (mangan)', '12000'],
      answer: 1,
      why: '5 han is a mangan whatever the fu.',
    },
    {
      kind: 'choice',
      prompt: 'What is a dealer 4 han 40 fu hand worth by ron?',
      options: ['12000 (mangan)', '11600', '8000'],
      answer: 0,
      why: '4 han 40 fu reaches the cap, and a dealer mangan is 12000.',
    },
  ],
  haneman: [
    {
      kind: 'choice',
      prompt: 'A non-dealer wins a 6 han hand by ron. How much?',
      options: ['8000', '12000', '16000'],
      answer: 1,
      why: '6 and 7 han are a haneman: one and a half mangan.',
    },
    {
      kind: 'choice',
      prompt: 'The dealer wins a 7 han hand by ron. How much?',
      options: ['12000', '24000', '18000'],
      answer: 2,
      why: '7 han is still a haneman, 18000 for the dealer.',
    },
    {
      kind: 'choice',
      prompt: 'A non-dealer wins a 9 han hand by ron. How much?',
      options: ['16000', '12000', '24000'],
      answer: 0,
      why: '8-10 han are a baiman: two mangan.',
    },
  ],
};
